import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Building2, CreditCard, Download, FileText, LayoutDashboard, LogOut, Package, ReceiptText, RefreshCw, Search, ShieldCheck, Users } from "lucide-react";
import "./portal.css";

const cash=(amount,currency="CAD")=>new Intl.NumberFormat("en-CA",{style:"currency",currency}).format(Number(amount||0)/100);
const day=(value)=>value?new Date(value).toLocaleDateString("en-CA",{month:"short",day:"numeric",year:"numeric"}):"-";
const demoAccount={id:"demo",organization_name:"Eitz Chaim Schools",account_code_hint:"AD-1048",billing_email:"billing@eitzchaim.com",billing_contact:"Raviv Talkar",status:"active",currency:"CAD",payment_terms_days:30,credit:{creditLimit:250000,postedBalance:122490,balance:122490,reserved:18500,available:109010},orders:[{id:"1",ordered_at:"2026-08-19",receipt_number:"HFEG",source:"in_store",status:"posted",total:5000,currency:"CAD"},{id:"2",ordered_at:"2026-08-19",receipt_number:"H86C",source:"online",status:"posted",total:16950,currency:"CAD"},{id:"3",ordered_at:"2026-07-13",receipt_number:"B2DC",source:"in_store",status:"posted",total:48025,currency:"CAD"}],ledger:[{id:"1",effective_at:"2026-08-19",description:"Online order H86C",transaction_type:"sale",amount:16950,currency:"CAD"},{id:"2",effective_at:"2026-07-17",description:"Credit adjustment",transaction_type:"credit",amount:-10000,currency:"CAD"}],statements:[{id:"demo-statement",statement_number:"AD-1048-20260821",period_start:"2026-07-13",period_end:"2026-08-21",due_at:"2026-09-20",closing_balance:122490,currency:"CAD",status:"issued"}],payments:[]};

async function request(path,options){const response=await fetch(`/api/house${path}`,{headers:{"Content-Type":"application/json",...(options?.headers||{})},...options});const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.error?.message||"Request failed.");return body;}

function App(){
  const demo=new URLSearchParams(location.search).has("demo");
  const [user,setUser]=useState(demo?{firstName:"Raviv",lastName:"Talkar",role:"owner",tenantName:"Amazing Donuts"}:undefined);
  const [accounts,setAccounts]=useState(demo?[demoAccount]:null),[account,setAccount]=useState(demo?demoAccount:null),[error,setError]=useState("");
  const staff=["owner","staff"].includes(user?.role);
  useEffect(()=>{if(demo)return;request("/auth/session").then(({user})=>setUser(user)).catch(()=>setUser(null));},[demo]);
  useEffect(()=>{if(!user||demo)return;(staff?request("/admin/accounts").then(({accounts})=>setAccounts(accounts)):request("/portal/account").then(({account})=>setAccount(account))).catch(cause=>setError(cause.message));},[user,staff,demo]);
  if(user===undefined)return <div className="boot">Loading account service...</div>;
  if(!user)return <Login onUser={setUser}/>;
  return <Shell user={user} onLogout={async()=>{if(!demo)await request("/auth/logout",{method:"POST"});setUser(null);}}>{staff?<Admin accounts={accounts} setAccounts={setAccounts} demo={demo}/>:<Customer account={account}/>}</Shell>;
}

function Login({onUser}){const [error,setError]=useState("");return <main className="login"><section className="login-brand"><div className="brand-mark">AD</div><p>Institutional ordering</p><h1>House accounts,<br/>without the paperwork pile.</h1><span>Secure account access for approved organizations.</span></section><section className="login-panel"><form onSubmit={async event=>{event.preventDefault();setError("");const data=Object.fromEntries(new FormData(event.currentTarget));try{const body=await request("/auth/login",{method:"POST",body:JSON.stringify({...data,tenant:"amazing-donuts"})});onUser(body.user);}catch(cause){setError(cause.message);}}}><ShieldCheck/><h2>Sign in</h2><label><span>Email address</span><input name="email" type="email" autoComplete="email" required/></label><label><span>Password</span><input name="password" type="password" autoComplete="current-password" minLength="8" required/></label>{error?<p className="error">{error}</p>:null}<button>Continue</button></form></section></main>}

function Shell({user,onLogout,children}){return <div className="shell"><aside><div className="side-brand"><div className="brand-mark">AD</div><div><strong>{user.tenantName||"Amazing Donuts"}</strong><span>House Accounts</span></div></div><nav><a className="active"><LayoutDashboard/> Overview</a><a><Building2/> Accounts</a><a><ReceiptText/> Statements</a><a><Package/> Orders</a><a><Users/> Purchasers</a></nav><div className="side-user"><div>{user.firstName?.[0]}{user.lastName?.[0]}</div><span><strong>{user.firstName} {user.lastName}</strong><small>{user.role}</small></span><button title="Sign out" onClick={onLogout}><LogOut/></button></div></aside><div className="workspace"><header><div><p>{new Date().toLocaleDateString("en-CA",{weekday:"long",month:"long",day:"numeric"})}</p><h1>{["owner","staff"].includes(user.role)?"House account control":"Your house account"}</h1></div><button className="icon-button" title="Refresh" onClick={()=>location.reload()}><RefreshCw/></button></header>{children}</div></div>}

function Admin({accounts,setAccounts,demo}){const [selected,setSelected]=useState(accounts?.[0]?.id),[query,setQuery]=useState("");useEffect(()=>{if(accounts?.length&&!selected)setSelected(accounts[0].id)},[accounts,selected]);const visible=(accounts||[]).filter(a=>a.organization_name.toLowerCase().includes(query.toLowerCase()));const account=(accounts||[]).find(a=>a.id===selected)||visible[0];const totals=(accounts||[]).reduce((sum,a)=>({owed:sum.owed+Number(a.credit?.balance||a.credit?.postedBalance||0),available:sum.available+Number(a.credit?.available||0),reserved:sum.reserved+Number(a.credit?.reserved||0)}),{owed:0,available:0,reserved:0});return <main className="dashboard"><section className="metrics"><Metric label="Receivables" value={cash(totals.owed)} note={`${accounts?.length||0} organizations`} tone="magenta"/><Metric label="Available credit" value={cash(totals.available)} note="Across active accounts" tone="green"/><Metric label="Reserved" value={cash(totals.reserved)} note="Pending online orders" tone="yellow"/></section><section className="admin-grid"><div className="account-list"><div className="section-head"><div><p>Portfolio</p><h2>Organizations</h2></div><label className="search"><Search/><input placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{visible.map(item=><button key={item.id} className={item.id===account?.id?"selected":""} onClick={()=>setSelected(item.id)}><span className="avatar">{item.organization_name.slice(0,2).toUpperCase()}</span><span><strong>{item.organization_name}</strong><small>{item.account_code_hint||item.billing_email}</small></span><b>{cash(item.credit?.balance||item.credit?.postedBalance,item.currency)}</b></button>)}</div>{account?<AccountDetail account={account} staff demo={demo} onChanged={next=>setAccounts(accounts.map(item=>item.id===next.id?next:item))}/>:<div className="empty">No account selected.</div>}</section></main>}

function Customer({account}){return <main className="dashboard">{account?<><section className="metrics"><Metric label="Balance due" value={cash(account.credit.balance||account.credit.postedBalance,account.currency)} note={`Net ${account.payment_terms_days}` } tone="magenta"/><Metric label="Available credit" value={cash(account.credit.available,account.currency)} note={`Limit ${cash(account.credit.creditLimit,account.currency)}`} tone="green"/><Metric label="Reserved" value={cash(account.credit.reserved,account.currency)} note="Pending orders" tone="yellow"/></section><AccountDetail account={account}/></>:<div className="empty">No house account is linked to this login.</div>}</main>}

function Metric({label,value,note,tone}){return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}

function AccountDetail({account,staff,demo}){const [tab,setTab]=useState("activity");const used=Number(account.credit.balance||account.credit.postedBalance||0),limit=Number(account.credit.creditLimit||0),percent=limit?Math.min(100,used/limit*100):0;return <article className="account-detail"><div className="account-title"><div><p>{account.account_code_hint||"House account"}</p><h2>{account.organization_name}</h2><span>{account.billing_contact} · {account.billing_email}</span></div><span className={`status ${account.status}`}>{account.status}</span></div><div className="credit-track"><div><span>Credit used</span><strong>{cash(used,account.currency)} <small>of {cash(limit,account.currency)}</small></strong></div><div className="track"><i style={{width:`${percent}%`}}/></div><p>{cash(account.credit.available,account.currency)} available · {cash(account.credit.reserved,account.currency)} reserved</p></div>{staff?<form className="controls" onSubmit={async event=>{event.preventDefault();if(demo)return;const data=new FormData(event.currentTarget);await request(`/admin/accounts/${account.id}`,{method:"PATCH",body:JSON.stringify({status:data.get("status"),creditLimit:Math.round(Number(data.get("limit"))*100),paymentTermsDays:Number(data.get("terms"))})});}}><label><span>Status</span><select name="status" defaultValue={account.status}><option>active</option><option>pending</option><option>suspended</option><option>closed</option></select></label><label><span>Credit limit</span><input name="limit" type="number" min="0" step=".01" defaultValue={limit/100}/></label><label><span>Terms</span><select name="terms" defaultValue={account.payment_terms_days}><option value="0">Due now</option><option value="15">Net 15</option><option value="30">Net 30</option><option value="45">Net 45</option><option value="60">Net 60</option></select></label><button>Save account</button></form>:null}<nav className="detail-tabs"><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>Activity</button><button className={tab==="statements"?"active":""} onClick={()=>setTab("statements")}>Statements</button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>Orders</button></nav>{tab==="activity"?<Activity entries={account.ledger}/>:tab==="statements"?<Statements account={account} staff={staff} demo={demo}/>:<Orders orders={account.orders}/>}</article>}

function Activity({entries=[]}){return <div className="table"><div className="table-head"><span>Date</span><span>Description</span><span>Type</span><span>Amount</span></div>{entries.length?entries.map(entry=><div className="table-row" key={entry.id}><span>{day(entry.effective_at)}</span><strong>{entry.description}</strong><em>{entry.transaction_type}</em><b className={Number(entry.amount)<0?"credit":""}>{cash(entry.amount,entry.currency)}</b></div>):<div className="empty-row">No account activity yet.</div>}</div>}
function Orders({orders=[]}){return <div className="table"><div className="table-head"><span>Date</span><span>Receipt</span><span>Channel</span><span>Total</span></div>{orders.length?orders.map(order=><div className="table-row" key={order.id}><span>{day(order.ordered_at)}</span><strong>#{order.receipt_number||String(order.square_order_id||order.id).slice(-8)}</strong><em>{order.source}</em><b>{cash(order.total,order.currency)}</b></div>):<div className="empty-row">No house-account orders yet.</div>}</div>}
function Statements({account,staff,demo}){return <div className="statements"><div className="table"><div className="table-head"><span>Period</span><span>Statement</span><span>Status</span><span>Amount</span></div>{account.statements?.length?account.statements.map(statement=><a className="table-row" key={statement.id} href={demo?"#":`/api/house/statements/${statement.id}.pdf`} target="_blank"><span>{day(statement.period_start)} - {day(statement.period_end)}</span><strong><FileText/> {statement.statement_number}</strong><em>{statement.status}</em><b>{cash(statement.closing_balance,statement.currency)} <Download/></b></a>):<div className="empty-row">No statements issued yet.</div>}</div>{staff?<form className="issue" onSubmit={async event=>{event.preventDefault();if(demo)return;const data=new FormData(event.currentTarget);await request(`/admin/accounts/${account.id}/statements`,{method:"POST",body:JSON.stringify({periodStart:data.get("from"),periodEnd:data.get("through")})});location.reload();}}><div><ReceiptText/><span><strong>Close a billing period</strong><small>Create an immutable statement snapshot and customer PDF.</small></span></div><label><span>From</span><input type="date" name="from" required/></label><label><span>Through</span><input type="date" name="through" required/></label><button>Issue statement</button></form>:null}</div>}

createRoot(document.getElementById("root")).render(<App/>);
