import { useEffect, useState } from 'react';
import { ArrowLeft, Building2, LogOut, Package, ReceiptText, UserRound } from 'lucide-react';
import AuthModal from '../shop/AuthModal';
import CommerceLogo from './CommerceLogo';
import '../index.css';
import '../components/brand/brand.css';
import '../shop/shop.css';
import './commerce.css';

const cash=(n:number,c='CAD')=>new Intl.NumberFormat('en-CA',{style:'currency',currency:c}).format(Number(n||0)/100);
const day=(v:string)=>new Date(v).toLocaleDateString('en-CA',{year:'numeric',month:'short',day:'numeric'});
async function api(path:string,options?:RequestInit){const response=await fetch(`/api/house${path}`,{headers:{'Content-Type':'application/json',...(options?.headers||{})},...options});const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.error?.message||'Request failed.');return body}

type View='orders'|'profile'|'house';

export default function AccountPage(){
  const [session,setSession]=useState<any>();
  const [orders,setOrders]=useState<any[]>([]);
  const [application,setApplication]=useState<any>();
  const [authOpen,setAuthOpen]=useState(false);
  const [view,setView]=useState<View>('orders');
  const [message,setMessage]=useState('');
  const load=()=>api('/storefront/session').then(async next=>{setSession(next);if(next.user){const [orderBody,applicationBody]=await Promise.all([api('/storefront/orders'),api('/storefront/house-application')]);setOrders(orderBody.orders);setApplication(applicationBody.application)}else setAuthOpen(true)}).catch(error=>setMessage(error.message));
  useEffect(()=>{void load()},[]);
  if(!session?.user)return <main className="commerce-shell account-gate"><a href="/shop/"><ArrowLeft/> Back to shop</a><section><UserRound/><h1>Your Amazing Donuts account</h1><p>Sign in to see orders, manage your details, and apply for house-account credit.</p><button onClick={()=>setAuthOpen(true)}>Sign in or create account</button></section><AuthModal open={authOpen} onClose={()=>setAuthOpen(false)} onSuccess={load}/></main>;
  return <main className="commerce-shell"><header className="commerce-top"><a href="/shop/"><ArrowLeft/> Shop</a><CommerceLogo/><button onClick={async()=>{await api('/auth/logout',{method:'POST'});location.assign('/shop/')}}><LogOut/> Sign out</button></header><div className="account-layout"><aside className="account-nav"><div className="account-person"><span>{session.user.firstName[0]}{session.user.lastName[0]}</span><strong>{session.user.firstName} {session.user.lastName}</strong><small>{session.user.email}</small></div><button className={view==='orders'?'active':''} onClick={()=>setView('orders')}><Package/> Orders</button><button className={view==='profile'?'active':''} onClick={()=>setView('profile')}><UserRound/> Profile</button><button className={view==='house'?'active':''} onClick={()=>setView('house')}><Building2/> House account</button>{session.houseAccount&&<div className="house-credit"><Building2/><strong>{session.houseAccount.organizationName}</strong><span>{cash(session.houseAccount.credit.available)} available</span></div>}</aside><section className="account-content">{view==='orders'?<Orders orders={orders}/>:view==='profile'?<Profile session={session} onSaved={()=>{setMessage('Profile updated.');void load()}}/>:<HouseAccount session={session} application={application} onApplied={next=>{setApplication(next);setMessage('House-account application submitted.')}}/>}{message&&<p className="account-message">{message}</p>}</section></div></main>;
}

function Orders({orders}:{orders:any[]}){return <><div className="commerce-heading"><p>Order history</p><h1>Your orders</h1></div>{orders.length?<div className="customer-orders">{orders.map(order=><article key={order.id}><header><div><span>{day(order.ordered_at)}</span><strong>Order #{order.square_order_id.slice(-8)}</strong></div><em>{order.status}</em></header><div>{(order.line_items||[]).map((line:any)=><p key={line.uid||line.name}><span>{line.name} × {line.quantity}</span><b>{cash(line.total_money?.amount,order.currency)}</b></p>)}</div><footer><span>{order.payment_method==='house_account'?'Pay on account':'Card'} · {order.fulfillment?.type}</span><strong>{cash(order.total,order.currency)}</strong></footer></article>)}</div>:<div className="no-orders"><ReceiptText/><h2>No orders yet</h2><p>Your completed website orders will appear here.</p><a href="/shop/">Start an order</a></div>}</>}

function Profile({session,onSaved}:{session:any;onSaved:()=>void}){const profile=session.profile||{};return <><div className="commerce-heading"><p>Account details</p><h1>Your profile</h1></div><form className="profile-form" onSubmit={async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));await api('/storefront/profile',{method:'PATCH',body:JSON.stringify({firstName:data.firstName,lastName:data.lastName,phone:data.phone,address:{addressLine1:data.addressLine1,addressLine2:data.addressLine2,locality:data.locality,administrativeDistrictLevel1:'ON',postalCode:data.postalCode,country:'CA'}})});onSaved()}}><label><span>First name</span><input name="firstName" defaultValue={profile.first_name} required/></label><label><span>Last name</span><input name="lastName" defaultValue={profile.last_name} required/></label><label><span>Email</span><input value={profile.email} disabled/></label><label><span>Phone</span><input name="phone" defaultValue={profile.default_phone||profile.phone||''}/></label><label className="wide"><span>Street address</span><input name="addressLine1" defaultValue={profile.default_address?.addressLine1||''}/></label><label><span>Unit</span><input name="addressLine2" defaultValue={profile.default_address?.addressLine2||''}/></label><label><span>City</span><input name="locality" defaultValue={profile.default_address?.locality||'Toronto'}/></label><label><span>Postal code</span><input name="postalCode" defaultValue={profile.default_address?.postalCode||''}/></label><button>Save profile</button></form></>}

function HouseAccount({session,application,onApplied}:{session:any;application:any;onApplied:(application:any)=>void}){
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  if(session.houseAccount)return <><div className="commerce-heading"><p>Business credit</p><h1>Your house account</h1></div><div className="house-application-status"><Building2/><h2>{session.houseAccount.organizationName}</h2><p>Your account is {session.houseAccount.status}. You currently have <strong>{cash(session.houseAccount.credit.available)}</strong> available.</p><a href="/accounts/">Open account statements and activity</a></div></>;
  if(application)return <><div className="commerce-heading"><p>Business credit</p><h1>House-account application</h1></div><div className={`house-application-status ${application.status}`}><Building2/><h2>{application.organization_name}</h2><strong>{application.status}</strong><p>{application.status==='pending'?'The bakery is reviewing your application. You can continue ordering by card while it is under review.':application.status==='rejected'?(application.review_notes||'The application was not approved. Contact the bakery if your circumstances have changed.'):'Your account has been approved. Refresh this page to access it.'}</p></div></>;
  return <><div className="commerce-heading"><p>Business credit</p><h1>Apply for a house account</h1></div><form className="house-application-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(event.currentTarget));try{const body=await api('/storefront/house-application',{method:'POST',body:JSON.stringify(data)});onApplied(body.application)}catch(cause){setError(cause instanceof Error?cause.message:'Application failed.')}finally{setBusy(false)}}}><label><span>Organization name</span><input name="organizationName" autoComplete="organization" required/></label><label><span>Organization type</span><select name="organizationType" required defaultValue=""><option value="" disabled>Choose one</option><option>School</option><option>Shul</option><option>Caterer</option><option>Event planner</option><option>Corporate or office</option><option>Other business</option></select></label><label><span>Phone</span><input name="phone" type="tel" defaultValue={session.profile?.default_phone||session.profile?.phone||''}/></label><label className="wide"><span>About your ordering needs</span><textarea name="notes" rows={5} maxLength={3000} placeholder="Typical order size, frequency, and billing contact details"/></label>{error&&<p className="checkout-error wide" role="alert">{error}</p>}<button className="wide" disabled={busy}>{busy?'Submitting...':'Submit application'}</button></form></>;
}
