import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Building2, CreditCard, LockKeyhole, ShoppingBag, Store, Truck } from 'lucide-react';
import { ShopProvider, money, useShop } from '../lib/shop';
import AuthModal from '../shop/AuthModal';
import CommerceLogo from './CommerceLogo';
import '../index.css';
import '../components/brand/brand.css';
import '../shop/shop.css';
import './commerce.css';
import './delivery.css';
import { customizationComplete, PRINT_PRODUCTS, type Customization } from '../lib/custom-order';
import BrandDatePicker from '../components/BrandDatePicker';
import AddressAutocomplete, { type Address, type SavedAddress } from '../components/AddressAutocomplete';
import { formatNorthAmericanPhone } from '../lib/phone';

type Session = { user:null|{firstName:string;lastName:string;email:string}; profile:null|{default_phone?:string;default_address?:Partial<Address>}; houseAccount:null|{id:string;organizationName:string;status:string;credit:{available:number};creditEnabled:boolean;card?:{brand?:string;last4?:string}} };
type SquareCard = { attach:(selector:string)=>Promise<void>; tokenize:(details:unknown)=>Promise<{status:string;token?:string;errors?:{message?:string}[]}>; destroy:()=>Promise<boolean> };
declare global { interface Window { Square?: { payments:(appId:string,locationId:string)=>{card:()=>Promise<SquareCard>} } } }

const blankAddress:Address={addressLine1:'',addressLine2:'',locality:'Toronto',administrativeDistrictLevel1:'ON',postalCode:'',country:'CA'};
const HOURS:Record<number,[number,number]|undefined>={0:[8*60,13*60],1:[7*60+30,16*60],2:[7*60+30,16*60],3:[7*60+30,16*60],4:[7*60+30,16*60],5:[7*60+30,14*60]};
const torontoISOString=(value:string)=>{const [date,time]=value.split('T'),[year,month,day]=date.split('-').map(Number),[hour,minute]=time.split(':').map(Number),wallClock=Date.UTC(year,month-1,day,hour,minute),probe=new Date(wallClock),parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(probe).filter(part=>part.type!=='literal').map(part=>[part.type,part.value])),offset=Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day),Number(parts.hour),Number(parts.minute))-wallClock;return new Date(wallClock-offset).toISOString()};
const localValue=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);
const nextOpen=(date:Date)=>{while(!HOURS[date.getDay()])date.setDate(date.getDate()+1);date.setHours(9,0,0,0);return localValue(date)};
const tomorrow=()=>nextOpen(new Date(Date.now()+86400000));
const printMinimum=()=>{const threshold=Date.now()+7*86400000,d=new Date(threshold);d.setHours(9,0,0,0);if(d.getTime()<threshold)d.setDate(d.getDate()+1);return nextOpen(d)};
const slotsFor=(dateValue:string)=>{const date=new Date(`${dateValue}T12:00:00`),window=HOURS[date.getDay()];if(!window)return [];return Array.from({length:(window[1]-window[0])/15+1},(_,index)=>{const minutes=window[0]+index*15,hour=Math.floor(minutes/60),minute=minutes%60,value=`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`,label=new Intl.DateTimeFormat('en-CA',{hour:'numeric',minute:'2-digit'}).format(new Date(2000,0,1,hour,minute));return {value,label}})};
async function api(path:string,options?:RequestInit){const response=await fetch(`/api/house${path}`,{headers:{'Content-Type':'application/json',...(options?.headers||{})},...options});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||'Request failed.');return body}

function Checkout(){
  const {lines,subtotal,customize,clear}=useShop();
  const customReady=lines.every(line=>customizationComplete(line.product.id,line.qty,line.customization));
  const requiresPrintLeadTime=lines.some(line=>PRINT_PRODUCTS.has(line.product.id));
  const scheduledMinimum=requiresPrintLeadTime?printMinimum():tomorrow();
  const [session,setSession]=useState<Session>();
  const [authOpen,setAuthOpen]=useState(false);
  const [method,setMethod]=useState<'card'|'house_account'>('card');
  const [authorizationPin,setAuthorizationPin]=useState('');
  const [fulfillment,setFulfillment]=useState<'pickup'|'delivery'>('pickup');
  const [scheduledAt,setScheduledAt]=useState(tomorrow);
  const [phone,setPhone]=useState('');
  const [address,setAddress]=useState<Address>(blankAddress);
  const [savedAddresses,setSavedAddresses]=useState<SavedAddress[]>([]);
  const [saveAddress,setSaveAddress]=useState(false);
  const [addressLabel,setAddressLabel]=useState('Home');
  const [addressType,setAddressType]=useState<'home'|'work'|'other'>('home');
  const [deliveryInstructions,setDeliveryInstructions]=useState('');
  const [noContact,setNoContact]=useState(false);
  const [config,setConfig]=useState<any>();
  const [quote,setQuote]=useState<any>();
  const [quoteError,setQuoteError]=useState('');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const [success,setSuccess]=useState<any>();
  const [confirmPayment,setConfirmPayment]=useState(false);
  const [saveCardForAccount,setSaveCardForAccount]=useState(false);
  const card=useRef<SquareCard|undefined>(undefined);
  const fulfillmentTimes=slotsFor(scheduledAt.slice(0,10));

  const loadSession=()=>api('/storefront/session').then(async body=>{setSession(body);setPhone(formatNorthAmericanPhone(body.profile?.default_phone||''));if(body.user){const saved=await api('/storefront/addresses');setSavedAddresses(saved.addresses||[]);setAddress({...blankAddress,...(saved.addresses?.find((item:SavedAddress)=>item.isDefault)||body.profile?.default_address||{})});}if(!body.user)setAuthOpen(true)}).catch(cause=>setError(cause.message));
  useEffect(()=>{void loadSession();void api('/storefront/config').then(setConfig).catch(cause=>setError(cause.message))},[]);
  useEffect(()=>{if(scheduledAt<scheduledMinimum)setScheduledAt(scheduledMinimum)},[scheduledAt,scheduledMinimum]);
  useEffect(()=>{if(fulfillmentTimes.length&&!fulfillmentTimes.some(slot=>slot.value===scheduledAt.slice(11,16)))setScheduledAt(`${scheduledAt.slice(0,10)}T${fulfillmentTimes[0].value}`)},[scheduledAt,fulfillmentTimes]);
  useEffect(()=>{if(!config?.applicationId||method!=='card'||!session?.user)return;let cancelled=false;const mount=async()=>{if(!window.Square){const script=document.createElement('script');script.src=config.environment==='sandbox'?'https://sandbox.web.squarecdn.com/v1/square.js':'https://web.squarecdn.com/v1/square.js';script.async=true;await new Promise<void>((resolve,reject)=>{script.onload=()=>resolve();script.onerror=()=>reject(new Error('Secure card fields could not load.'));document.head.appendChild(script)})}if(cancelled||!window.Square)return;card.current=await window.Square.payments(config.applicationId,config.locationId).card();await card.current.attach('#square-card')};void mount().catch(cause=>setError(cause.message));return()=>{cancelled=true;void card.current?.destroy().catch(()=>{});card.current=undefined}},[config,method,session?.user]);

  const items=()=>lines.map(line=>({name:line.product.name,quantity:line.qty}));
  const fulfillmentBody=()=>({type:fulfillment,scheduledAt:torontoISOString(scheduledAt),recipient:{displayName:`${session?.user?.firstName||''} ${session?.user?.lastName||''}`.trim(),email:session?.user?.email||'',phone},...(fulfillment==='delivery'?{address,deliveryInstructions,noContact}:{})});
  useEffect(()=>{
    if(!session?.user||!lines.length||!customReady||!phone||!scheduledAt||(fulfillment==='delivery'&&(!address.addressLine1||address.postalCode.replace(/\s/g,'').length<6))){setQuote(undefined);setQuoteError('');return}
    const controller=new AbortController();
    const timer=window.setTimeout(()=>{api('/storefront/quote',{method:'POST',signal:controller.signal,body:JSON.stringify({items:items(),fulfillment:fulfillmentBody()})}).then(body=>{setQuote(body);setQuoteError('')}).catch(cause=>{if(cause.name!=='AbortError'){setQuote(undefined);setQuoteError(cause.message)}})},350);
    return()=>{window.clearTimeout(timer);controller.abort()};
  },[session?.user,lines,customReady,phone,scheduledAt,fulfillment,address,deliveryInstructions,noContact]);

  const uploadCustomizations=async()=>{const output:{productName:string;kind:string;glyph?:string;icingFlavor?:string;sprinkleColours?:string;artworks?:{assetId:string;count:number}[]}[]=[];for(const line of lines){const custom=line.customization;if(custom?.kind==='glyph')output.push({productName:line.product.name,kind:'glyph',glyph:custom.glyph});if(custom?.kind==='print'){const artworks:{assetId:string;count:number}[]=[],updated=[];for(const art of custom.artworks){let assetId=art.assetId;if(!assetId){const body=await api('/storefront/custom-assets',{method:'POST',body:JSON.stringify({fileName:art.name,dataUrl:art.dataUrl})});assetId=body.asset.id as string}if(!assetId)throw new Error('Artwork upload failed.');artworks.push({assetId,count:art.count});updated.push({...art,assetId})}const next:Customization={...custom,artworks:updated};customize(line.product.id,next);output.push({productName:line.product.name,kind:'print',icingFlavor:custom.icingFlavor,sprinkleColours:custom.sprinkleColours,artworks})}}return output;};

  const place=async(event?:React.FormEvent,cardConfirmed=false)=>{event?.preventDefault();if(!session?.user){setAuthOpen(true);return}if(!lines.length||!customReady||!quote)return;if(method==='card'&&session.houseAccount?.status==='active'&&!session.houseAccount.card&&!saveCardForAccount&&!cardConfirmed){setConfirmPayment(true);return}setConfirmPayment(false);setBusy(true);setError('');try{if(fulfillment==='delivery'&&saveAddress&&!savedAddresses.some(item=>sameAddress(item,address))){const saved=await api('/storefront/addresses',{method:'POST',body:JSON.stringify({...address,label:addressLabel,addressType,isDefault:savedAddresses.length===0})});setSavedAddresses(current=>[...current,saved.address]);setSaveAddress(false);}let sourceId:string|undefined;if(method==='card'){if(!card.current)throw new Error('The secure card form is still loading.');const shouldSave=Boolean(session.houseAccount?.status==='active'&&!session.houseAccount.card&&saveCardForAccount),token=await card.current.tokenize(shouldSave?{intent:'STORE',customerInitiated:true,sellerKeyedIn:false,billingContact:{givenName:session.user.firstName,familyName:session.user.lastName,email:session.user.email,phone}}:{amount:(quote.order.total/100).toFixed(2),currencyCode:quote.order.currency,intent:'CHARGE',customerInitiated:true,sellerKeyedIn:false,billingContact:{givenName:session.user.firstName,familyName:session.user.lastName,email:session.user.email,phone,addressLines:[address.addressLine1,address.addressLine2].filter(Boolean),city:address.locality,state:address.administrativeDistrictLevel1,postalCode:address.postalCode,countryCode:address.country}});if(token.status!=='OK'||!token.token)throw new Error(token.errors?.[0]?.message||'Card authorization failed.');if(shouldSave){await api('/storefront/house-card',{method:'POST',body:JSON.stringify({sourceId:token.token,consent:true,cardholderName:`${session.user.firstName} ${session.user.lastName}`})});sourceId='SAVED_CARD'}else sourceId=token.token}const customizations=await uploadCustomizations();const result=await api('/storefront/checkout',{method:'POST',body:JSON.stringify({idempotencyKey:crypto.randomUUID(),items:items(),customizations,fulfillment:fulfillmentBody(),paymentMethod:method,sourceId,authorizationPin:method==='house_account'?authorizationPin:undefined})});clear();setSuccess({...result.order,delivery:result.delivery})}catch(cause){setError(cause instanceof Error?cause.message:'Checkout failed.')}finally{setBusy(false)}};
  const saveAndUseCredit=async()=>{if(!session?.user||!card.current||!quote)return;setConfirmPayment(false);setBusy(true);setError('');try{const token=await card.current.tokenize({intent:'STORE',customerInitiated:true,sellerKeyedIn:false,billingContact:{givenName:session.user.firstName,familyName:session.user.lastName,email:session.user.email,phone}});if(token.status!=='OK'||!token.token)throw new Error(token.errors?.[0]?.message||'Card authorization failed.');await api('/storefront/house-card',{method:'POST',body:JSON.stringify({sourceId:token.token,consent:true,cardholderName:`${session.user.firstName} ${session.user.lastName}`})});const customizations=await uploadCustomizations();const result=await api('/storefront/checkout',{method:'POST',body:JSON.stringify({idempotencyKey:crypto.randomUUID(),items:items(),customizations,fulfillment:fulfillmentBody(),paymentMethod:'house_account',authorizationPin})});clear();setSuccess({...result.order,delivery:result.delivery})}catch(cause){setError(cause instanceof Error?cause.message:'Card could not be saved.')}finally{setBusy(false)}};

  if(success)return <main className="commerce-shell"><section className="commerce-success"><ShoppingBag/><p>Order confirmed</p><h1>Your box is on the bakery's list.</h1><strong>Order #{success.id.slice(-8)}</strong><span>{money(success.total/100)} · {fulfillment}</span>{success.delivery&&<small>Delivery is awaiting assignment by the bakery.</small>}<a href="/account/">View my orders</a></section></main>;
  const payable=quote?.order?.total/100;
  return <main className="commerce-shell">
    <header className="commerce-top"><a href="/shop/"><ArrowLeft/> Back to the shop</a><CommerceLogo/><a href="/account/">My account</a></header>
    <div className="checkout-grid"><form className="checkout-form" onSubmit={place}>
      <div className="commerce-heading"><p>Secure checkout</p><h1>Finish your order</h1><span><LockKeyhole/> Sign-in is required. Guest checkout is not available.</span></div>
      {session?.user?<section className="signed-row"><div><strong>{session.user.firstName} {session.user.lastName}</strong><span>{session.user.email}</span></div><a href="/account/">Manage account</a></section>:<section className="signin-gate"><h2>Sign in to continue</h2><p>Your cart is saved while you sign in or create an account.</p><button type="button" onClick={()=>setAuthOpen(true)}>Sign in or create account</button></section>}
      <fieldset disabled={!session?.user||busy}><legend>Fulfillment</legend>
        <div className="segment"><button type="button" className={fulfillment==='pickup'?'active':''} onClick={()=>setFulfillment('pickup')}><Store/> Pickup</button><button type="button" className={fulfillment==='delivery'?'active':''} disabled={config?.delivery?.enabled===false} onClick={()=>setFulfillment('delivery')}><Truck/> Delivery</button></div>
        {fulfillment==='delivery'&&config?.delivery&&<p className="delivery-policy">Local delivery is {money(config.delivery.feeAmount/100)} and free on merchandise orders of {money(config.delivery.freeThreshold/100)} or more. {money(config.delivery.minimumAmount/100)} minimum.</p>}
        <div className="fulfillment-schedule"><div className="checkout-date-field"><span>Date</span><BrandDatePicker value={scheduledAt.slice(0,10)} min={scheduledMinimum.slice(0,10)} onChange={value=>setScheduledAt(`${value}T09:00`)} ariaLabel="Choose a pickup or delivery date" disabledDay={day=>!HOURS[day.getDay()]}/></div><label><span>Time</span><select value={fulfillmentTimes.length?scheduledAt.slice(11,16):''} disabled={!fulfillmentTimes.length} onChange={event=>setScheduledAt(`${scheduledAt.slice(0,10)}T${event.target.value}`)} required>{fulfillmentTimes.length?fulfillmentTimes.map(slot=><option value={slot.value} key={slot.value}>{slot.label}</option>):<option value="">Closed</option>}</select></label>{requiresPrintLeadTime&&<small>Custom-printed items require at least one week's notice.</small>}<small className="schedule-hours">Sunday 8am–1pm · Monday–Thursday 7:30am–4pm · Friday 7:30am–2pm · Saturday closed. Times are in 15-minute intervals.</small></div>
        <label><span>Phone</span><input type="tel" value={phone} onChange={event=>setPhone(formatNorthAmericanPhone(event.target.value))} autoComplete="tel" required/></label>
        {fulfillment==='delivery'&&<div className="address-fields">{savedAddresses.length>0&&<label className="saved-address-select"><span>Saved address</span><select value={savedAddresses.find(item=>sameAddress(item,address))?.id||''} onChange={event=>{const selected=savedAddresses.find(item=>item.id===event.target.value);if(selected)setAddress(addressValue(selected));}}><option value="">Use another address</option>{savedAddresses.map(item=><option key={item.id} value={item.id}>{item.label}{item.isDefault?' · Default':''}</option>)}</select></label>}<label><span>Street address</span><AddressAutocomplete address={address} onChange={setAddress} enabled={config?.placesEnabled} required/></label><label><span>Unit</span><input value={address.addressLine2} onChange={event=>setAddress({...address,addressLine2:event.target.value})} autoComplete="address-line2"/></label><label><span>City</span><input value={address.locality} onChange={event=>setAddress({...address,locality:event.target.value})} autoComplete="address-level2" required/></label><label><span>Postal code</span><input value={address.postalCode} onChange={event=>setAddress({...address,postalCode:event.target.value.toUpperCase()})} autoComplete="postal-code" required/></label>{!savedAddresses.some(item=>sameAddress(item,address))&&<div className="save-address-row"><label className="no-contact"><input type="checkbox" checked={saveAddress} onChange={event=>setSaveAddress(event.target.checked)}/><span>Save this address</span></label>{saveAddress&&<><label><span>Label</span><input value={addressLabel} onChange={event=>setAddressLabel(event.target.value)} placeholder="Home, Work..." required/></label><label><span>Type</span><select value={addressType} onChange={event=>setAddressType(event.target.value as typeof addressType)}><option value="home">Home</option><option value="work">Work</option><option value="other">Other</option></select></label></>}</div>}<label className="delivery-instructions"><span>Drop-off instructions</span><textarea value={deliveryInstructions} onChange={event=>setDeliveryInstructions(event.target.value)} maxLength={500} rows={3}/></label><label className="no-contact"><input type="checkbox" checked={noContact} onChange={event=>setNoContact(event.target.checked)}/><span>No-contact delivery</span></label></div>}
      </fieldset>
      <fieldset disabled={!session?.user||busy}><legend>Payment</legend><div className="payment-options"><button type="button" className={method==='card'?'active':''} onClick={()=>setMethod('card')}><CreditCard/><span><strong>Card</strong><small>Securely processed by Square</small></span></button>{session?.houseAccount?.status==='active'&&session.houseAccount.creditEnabled&&<button type="button" className={method==='house_account'?'active':''} onClick={()=>setMethod('house_account')}><Building2/><span><strong>Pay on account</strong><small>{session.houseAccount.organizationName} · {money(session.houseAccount.credit.available/100)} credit available</small></span></button>}</div>{method==='card'&&<div id="square-card" className="square-card"/>}{method==='card'&&session?.houseAccount?.status==='active'&&!session.houseAccount.card&&<label className="save-card-choice"><input type="checkbox" checked={saveCardForAccount} onChange={event=>setSaveCardForAccount(event.target.checked)}/><span><strong>Save this card for {session.houseAccount.organizationName}</strong><small>The current order will be charged now. The card will also enable institutional credit and authorized statement collection.</small></span></label>}{method==='house_account'&&<><p className="house-note">This order will be added to your account balance and included on your next statement.</p><label><span>Authorization PIN</span><input type="password" inputMode="numeric" pattern="[0-9]{4,8}" minLength={4} maxLength={8} value={authorizationPin} onChange={event=>setAuthorizationPin(event.target.value)} autoComplete="off" required/></label></>}</fieldset>
      {(quoteError||error)&&<p className="checkout-error" role="alert">{quoteError||error}</p>}
      <button className="place-order" disabled={!session?.user||!lines.length||!customReady||!quote||busy}>{busy?'Uploading artwork and placing order...':!customReady?'Finish custom items in your cart':quote?`Place order · ${money(payable)}`:'Calculating Square total...'}</button>
    </form><aside className="order-summary"><p>Your box</p><h2>{lines.reduce((total,line)=>total+line.qty,0)} items</h2>{lines.map(line=><div className="summary-line" key={line.product.id}><img src={line.product.img} alt=""/><span><strong>{line.product.name}</strong><small>Qty {line.qty}</small></span><b>{money(Number(line.product.price.replace(/[^0-9.]/g,''))*line.qty)}</b></div>)}<div className="summary-breakdown"><span>Merchandise</span><b>{quote?money((quote.order.subtotal-(quote.delivery?.fee||0))/100):money(subtotal)}</b>{quote?.delivery&&<><span>Delivery</span><b>{quote.delivery.free?'Free':money(quote.delivery.fee/100)}</b></>}{quote&&<><span>HST</span><b>{money(quote.order.tax/100)}</b></>}</div><div className="summary-total"><span>{quote?'Total':'Estimated subtotal'}</span><strong>{money(quote?payable:subtotal)}</strong></div><small>{quote?.delivery?'The bakery assigns the driver after payment. Square does not dispatch the courier.':'Square confirms catalog pricing, HST, discounts, and the final total before payment.'}</small></aside></div>
    <AuthModal open={authOpen} onClose={()=>setAuthOpen(false)} onSuccess={loadSession}/>
    {confirmPayment&&<div className="payment-confirm-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setConfirmPayment(false)}}><section className="payment-confirm" role="dialog" aria-modal="true" aria-labelledby="payment-confirm-title"><CreditCard/><p>Confirm payment</p><h2 id="payment-confirm-title">How would you like to pay?</h2><span>{session?.houseAccount?.creditEnabled?'Your card can be charged now, or this order can use your approved account credit.':'Pay this order now without saving it, or save the card and use account credit.'}</span>{!session?.houseAccount?.creditEnabled?<label><span>Institutional account PIN</span><input type="password" inputMode="numeric" pattern="[0-9]{4,8}" minLength={4} maxLength={8} value={authorizationPin} onChange={event=>setAuthorizationPin(event.target.value)} /></label>:null}<div><button type="button" onClick={()=>void place(undefined,true)}>Pay this order now · {money(payable)}</button>{session?.houseAccount?.creditEnabled?<button type="button" onClick={()=>{setMethod('house_account');setConfirmPayment(false)}}>Use account credit</button>:<button type="button" disabled={authorizationPin.length<4} onClick={()=>void saveAndUseCredit()}>Save card and use account credit</button>}</div><button className="payment-confirm-cancel" type="button" onClick={()=>setConfirmPayment(false)}>Return to checkout</button></section></div>}
  </main>;
}

export default function CheckoutPage(){return <ShopProvider><Checkout/></ShopProvider>}
const addressValue=(address:Address):Address=>({addressLine1:address.addressLine1,addressLine2:address.addressLine2||'',locality:address.locality,administrativeDistrictLevel1:address.administrativeDistrictLevel1||'ON',postalCode:address.postalCode,country:address.country||'CA'});
const sameAddress=(left:Address,right:Address)=>left.addressLine1===right.addressLine1&&left.addressLine2===right.addressLine2&&left.postalCode===right.postalCode;
