import { FileImage, Plus, X } from 'lucide-react';
import { customizationFor, imageDataUrl, type Customization } from '../lib/custom-order';

export default function CartCustomization({productId,qty,value,onChange}:{productId:string;qty:number;value?:Customization;onChange:(next:Customization)=>void}){
  const customization=value||customizationFor(productId);
  if(!customization)return null;
  if(customization.kind==='glyph')return <div className="cart-custom"><label><span>Cake specifications</span><textarea className="cart-glyph" value={customization.glyph} maxLength={120} rows={2} placeholder="Examples: 20, MAZEL TOV, A & J" onChange={event=>onChange({kind:'glyph',glyph:event.target.value.toUpperCase()})}/></label><small>Enter the letters, numbers, or short message the bakery should shape. {customization.glyph.length}/120</small></div>;
  const total=qty,assigned=customization.artworks.reduce((sum,art)=>sum+art.count,0),remaining=Math.max(0,total-assigned);
  const withPrint=(patch:Partial<typeof customization>)=>onChange({...customization,...patch});
  const update=(key:string,patch:Record<string,unknown>)=>withPrint({artworks:customization.artworks.map(art=>art.key===key?{...art,...patch}:art)});
  const remove=(key:string)=>withPrint({artworks:customization.artworks.filter(art=>art.key!==key)});
  const upload=async(file?:File)=>{if(!file)return;const dataUrl=await imageDataUrl(file);withPrint({artworks:[...customization.artworks,{key:crypto.randomUUID(),name:file.name,dataUrl,count:Math.min(4,remaining)}]});};
  return <div className="cart-custom"><div className="cart-print-options"><label><span>Icing flavour</span><select value={customization.icingFlavor} required onChange={event=>withPrint({icingFlavor:event.target.value as 'Chocolate'|'Vanilla'})}><option value="">Choose icing</option><option>Chocolate</option><option>Vanilla</option></select></label><label><span>Sprinkle colours</span><input value={customization.sprinkleColours} maxLength={120} placeholder="Optional" onChange={event=>withPrint({sprinkleColours:event.target.value})}/></label></div><div className="cart-custom__head"><strong>Print artwork</strong><span>{assigned}/{total} dozen units assigned</span></div>{customization.artworks.map((art,index)=><div className="cart-art" key={art.key}><img src={art.dataUrl} alt=""/><span><strong>Design {index+1}</strong><small>{art.name}</small></span><label><span>Dozens</span><input type="number" min="1" max={Math.min(4,art.count+remaining)} value={art.count} onChange={event=>update(art.key,{count:Math.max(1,Math.min(4,art.count+remaining,Number(event.target.value)||1))})}/></label><button type="button" onClick={()=>remove(art.key)} aria-label={`Remove ${art.name}`}><X/></button></div>)}{remaining>0&&<label className="cart-upload"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>{void upload(event.target.files?.[0]);event.currentTarget.value=''}}/><FileImage/><span><strong>{customization.artworks.length?'Add another design':'Choose print file'}</strong><small>This design covers {Math.min(4,remaining)} dozen unit{Math.min(4,remaining)===1?'':'s'}</small></span><Plus/></label>}{remaining===0&&<small className="cart-custom__ready">All {total} dozen units are assigned.</small>}</div>;
}
